export { default as Jumbotron } from './jumbotron/Jumbotron';
export { default as Footer } from './footer/Footer';
export { default as Accordion } from './accordion/Accordion';
export { default as OptForm } from './opt-form/OptForm';
export { default as Header } from './header/Header';
export { default as Feature } from './feature/Feature';
export { default as Form } from './form/Form';
export { default as Profile } from './profile/Profile';
export { default as Loading } from './loading/Loading';
